### ISSUE TITLE
Support for RegExp

### ISSUE THREAD

**Issue by pundoo** [AngelAngelov/deepCopy#1]
First of all thanks a ton for this awesome script :) saved me a lot of time.

However, one little thing I am experiencing is that, RegExp values are not getting cloned :(

Could you please also add support for that?

**Comment by AngelAngelov** [comment]
Thank you for your feedback. I am glad you like the library .I will ad support RegEx  ASAP.

**Comment by AngelAngelov** [comment]
Support for RegExp is added, so I am closing the issue.

**Comment by pundoo** [comment]
**Awesome!**
Could it also be possible to add support for cloning properties & methods under prototype?

**Comment by AngelAngelov** [comment]
It's fixed. You can try it now. If you find some issue let me know, because it was a quick fix and just one test :)

**Comment by pundoo** [comment]
**Perfect!**
 Thank you so much. You're a life saver :)

**Just one issue :**  static class methods are still keeping reference.. see [here](https://jsfiddle.net/4wgtkwpd/)
